_defaults:
  kongctl:
    namespace: customer

control_planes:
  - ref: customer-data-dev
    _external:
      selector:
        matchFields:
          name: customer-data-dev
    _deck:
      files:
        - ../gateway/dev/kong.yaml
      flags:
        - --analytics=false

apis:
  - ref: customer-information-dev-api
    name: KongAir Customer Information - Development
    description: Development Catalog API owned by the Customer service team.
    versions:
      - ref: customer-information-dev-0-1-0
        version: !file ../openapi.yaml#info.version
        spec: !file ../openapi.yaml
    publications:
      - ref: customer-information-dev-publication
        portal_id: !lookup {name: KongAirlines Development}
        visibility: private
        auth_strategy_ids:
          - !lookup {name: kongairlines-key-auth-dev}
    implementations:
      - ref: customer-information-dev-control-plane
        type: control_plane
        control_plane:
          control_plane_id: !ref customer-data-dev#id
